
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    metallb.universe.tf/allow-shared-ip: usdf-prompt-processing-dev
  name: kourier
  namespace: knative-serving
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    metallb.universe.tf/allow-shared-ip: usdf-prompt-processing-dev
spec:
  type: LoadBalancer
