apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: HTTP_PROXY
              value: http://sdfproxy.sdf.slac.stanford.edu:3128
            - name: HTTPS_PROXY
              value: http://sdfproxy.sdf.slac.stanford.edu:3128
            - name: NO_PROXY
              vaue: .cluster.local,.svc,.slac.stanford.edu

