
bases:
- knative-operator/
- cnpg-operator/
- database/

resources:
- knative-serving.yaml
- knative-eventing.yaml
- kafka-knative.yaml

# can't include in kustomize as its not local
#patches:
#- knative-serving-patch.yaml

secretGenerator:
- name: usdf-prompt-processing-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

- name: usdf-butler-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/butler/username
  - etc/.secrets/butler/password
