
namespace: knative-serving
resources:
- ns.yaml
- kourier.yaml
- serving-core-1.10.1.yaml
- serving-crds-1.10.1.yaml
- knative-config-defaults.yaml
- knative-config-features.yaml
- knative-config-gc.yaml
- knative-config-logging.yaml
- knative-config-observability.yaml