apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.2.3
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        authentication:
          type: scram-sha-512
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        tls: true
        type: loadbalancer
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            annotations:
              metallb.universe.tf/address-pool: sdf-services
          brokers:
          - broker: 0
            annotations:
              metallb.universe.tf/address-pool: sdf-services
    authorization:
      type: simple
      superUsers:
        - CN=knative-broker-user
        - knative-broker-sasl
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
      # ssl.endpoint.identification.algorithm: ""
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
