apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: prompt-processing
  namespace: kafka
spec:
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    logging: debug
    enableSaramaLogging: true
    template:
      deployment:
        metadata:
          annotations:
            prometheus.io/scrape: 'true'      
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: 'true'
  kafka:
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: 'true'
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        tls: false
        type: loadbalancer
        configuration:
          bootstrap:
            annotations:
              metallb.universe.tf/address-pool: sdf-services
          brokers:
          - broker: 0
            annotations:
              metallb.universe.tf/address-pool: sdf-services
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
