apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: test
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/prompt-proto/prompt/nextvisit-start
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - consumer-dep.yaml
