apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prompt-proto-service
  namespace: prompt-proto-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/min-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/target-utilization-percentage: "60"
        autoscaling.knative.dev/target-burst-capacity: "-1"
        # Update this field if `make apply` by itself doesn't make a new revision.
        revision: "32"
      creationTimestamp: null
    spec:
      containerConcurrency: 1
      containers:
      - image: us-central1-docker.pkg.dev/prompt-proto/prompt/prompt-proto-service:latest
        imagePullPolicy: Always
        name: user-container
        env:
        - name: RUBIN_INSTRUMENT
          value: HSC
        - name: PIPELINES_CONFIG
          value: (survey="SURVEY")=[${PROMPT_PROTOTYPE_DIR}/pipelines/${RUBIN_INSTRUMENT}/ApPipe.yaml]
        - name: SKYMAP
          value: hsc_rings_v1
        - name: PUBSUB_VERIFICATION_TOKEN
          value: rubin-prompt-proto-main
        - name: IMAGE_BUCKET
          value: rubin:rubin-pp
        - name: BUCKET_TOPIC
          value: rubin-prompt-processing
        - name: IMAGE_TIMEOUT
          value: '120'
        - name: CALIB_REPO
          value: s3://rubin:rubin-pp-users/central_repo/
        - name: LSST_DISABLE_BUCKET_VALIDATION
          value: '1'
        - name: IP_APDB
          # Need explicit port for make_pgpass.py
          value: usdf-prompt-processing-dev.slac.stanford.edu:5432
        - name: DB_APDB
          value: lsst-devl
        - name: USER_APDB
          value: rubin
        - name: NAMESPACE_APDB
          value: pp_apdb
        - name: IP_REGISTRY
          # Need explicit port for make_pgpass.py
          value: usdf-prompt-processing-dev.slac.stanford.edu:5432
        - name: DB_REGISTRY
          value: ppcentralbutler
        - name: USER_REGISTRY
          value: pp
        - name: KAFKA_CLUSTER
          value: prompt-processing-kafka-bootstrap.kafka:9092
        - name: PSQL_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: usdf-pp-creds
              key: password
        - name: PSQL_APDB_PASS
          valueFrom:
            secretKeyRef:
              name: usdf-prompt-processing-creds
              key: password
        - name: S3_ENDPOINT_URL
          value: https://s3dfrgw.slac.stanford.edu
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /app/s3/credentials
        - name: LOCAL_REPOS
          value: "/tmp-butler"
        volumeMounts:
          - mountPath: /app/s3/credentials
            name: s3-credentials-file
            subPath: credentials
          - mountPath: /tmp-butler
            name: ephemeral
            readOnly: false
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          requests:
            ephemeral-storage: "8Gi"
          limits:
            ephemeral-storage: "20Gi"
      volumes:
      - name: s3-credentials-file
        secret:
          secretName: s3-credentials-file-v6
      - name: ephemeral
        emptyDir:
          sizeLimit: "20Gi"
      enableServiceLinks: false
      imagePullSecrets:
      - name: regcred
      timeoutSeconds: 900
      idleTimeoutSeconds: 900
      responseStartTimeoutSeconds: 900
