apiVersion: v1
data:
  loglevel.controller: {{ .Values.logging.controllerLogLevel }}
  loglevel.autoscaler: {{ .Values.logging.autoscalerLogLevel }}
  loglevel.queueproxy: {{ .Values.logging.queueproxyLogLevel }}
  loglevel.activator: {{ .Values.logging.activatorLogLevel }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: knative-serving
  name: config-logging
  namespace: knative-serving