apiVersion: v1
data:
  kubernetes.podspec-persistent-volume-claim: {{ .Values.features.persistentVolumeClaim }}
  kubernetes.podspec-volumes-emptydir: {{ .Values.features.emptydir }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
  name: config-features
  namespace: knative-serving