apiVersion: v1
data:
  max-non-active-revisions: {{ .Values.garbageCollection.maxNonActiveRevisions }}
  min-non-active-revisions: {{ .Values.garbageCollection.minNonActiveRevisions }}
  retain-since-create-time: {{ .Values.garbageCollection.retainSinceCreateTime }}
  retain-since-last-active-time: {{ .Values.garbageCollection.retainSinceLastActiveTime }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
  name: config-gc
  namespace: knative-serving
