# Default values for latiss prompt-proto-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: ghcr.io/lsst-dm/prompt-proto-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: d_2023_07_11

instrument:
  name: LATISS
  pipelines:
  skymap: latiss_v1
  calibRepo: /app/butler

s3:
  imageBucket: rubin-summit
  endpointUrl: https://s3dfrgw.slac.stanford.edu
  auth_env: true

imageNotifications:
  kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
  topic: rubin-prompt-processing-prod
  imageTimeout: '120'

apdb:
  ip: usdf-prompt-processing.slac.stanford.edu:5432
  db: lsst-devl
  user: rubin
  namespace: pp_apdb

registry:
  ip: usdf-butler.slac.stanford.edu:5432
  db: lsstdb1
  user: rubin

knative:
  minScale: 3
  maxScale: 100
  ephemeralStorageRequest: "8Gi"
  ephemeralStorageLimit: "20Gi"
  timeout: 900

namespace: prompt-proto-service-latiss