# Default values for hsc prompt-proto-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: ghcr.io/lsst-dm/prompt-proto-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: d_2023_07_11

instrument:
  name: HSC
  pipelines: (survey="SURVEY")=[${PROMPT_PROTOTYPE_DIR}/pipelines/HSC/ApPipe.yaml]
  skymap: hsc_rings_v1
  calibRepo: s3://rubin-pp-users/central_repo/

s3:
  imageBucket: rubin-pp
  endpointUrl: https://s3dfrgw.slac.stanford.edu
  cred_file_auth: true

imageNotifications:
  kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
  topic: rubin-prompt-processing
  imageTimeout: '120'

apdb:
  ip: usdf-prompt-processing-dev.slac.stanford.edu:5432
  db: lsst-devl
  user: rubin
  namespace: pp_apdb

registry:
  ip: usdf-prompt-processing-dev.slac.stanford.edu:5432
  db: ppcentralbutler
  user: pp

knative:
  minScale: 3
  maxScale: 100
  ephemeralStorageRequest: "8Gi"
  ephemeralStorageLimit: "20Gi"
  timeout: 900

namespace: prompt-proto-service-hsc

additionalVolumeMounts:
  - mountPath: /app/s3/credentials
    name: s3-credentials-file
    subPath: credentials