namespace: database

resources:
- ns.yaml
- cnpg-database.yaml
- cnpg-pooler.yaml
- lb-svc.yaml

secretGenerator:
- name: usdf-prompt-processing-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
