apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: next-visit-test-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: prompt-processing
spec:
  partitions: 1
  replicas: 1