apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-test
  namespace: knative-eventing
spec:
  template:
    spec:
      containers:
      - name: kafka-producer-test
        image: us-central1-docker.pkg.dev/prompt-proto/prompt/usdf-kafka-producer-test:v1.6
        command: [ "python3", "main.py"]
        env:
          - name: KAFKA_CLUSTER
            value: my-cluster-kafka-bootstrap.kafka:9092
          - name: BUCKET_NOTIFY_TOPIC
            value: next-visit-topic
          - name: SASL_USERNAME
            valueFrom:
              secretKeyRef:
                name: knative-broker-sasl
                key: user
          - name: SASL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: knative-broker-sasl
                  key: password
          - name: SASL_MECHANISM
            value: SCRAM-SHA-512
          - name: SECURITY_PROTOCOL
            value: SASL_PLAINTEXT
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 2