apiVersion: batch/v1
kind: Job
metadata:
  name: nextvisit-producer-
  namespace: knative-eventing
spec:
  template:
    spec:
      containers:
      - name: nextvisit-producer
        image: us-central1-docker.pkg.dev/prompt-proto/prompt/usdf-kafka-producer-nextvisit:945e3a1-dirty
        command: [ "python3", "main.py"]
        env:
          - name: KAFKA_CLUSTER
            value: prompt-processing-kafka-bootstrap.kafka:9092
          - name: BUCKET_NOTIFY_TOPIC
            value: next-visit-test-topic
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 2