apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-visit-fan-out
  namespace: next-visit-fan-out
  labels:
    app: next-visit-fan-out
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-visit-fan-out
  template:
    metadata:
      labels:
        app: next-visit-fan-out
    spec:
      containers:
        - name: nextvisit-start
          image: ghcr.io/lsst-dm/next_visit_fan_out:main
          imagePullPolicy: Always
          env:
            - name: LATISS_KNATIVE_SERVING_URL
              value: http://prompt-proto-service.prompt-proto-service/next-visit
            - name: HSC_KNATIVE_SERVING_URL
              value: http://prompt-proto-service.prompt-proto-service/next-visit
            - name: LSST_CAM_KNATIVE_SERVING_URL
              value: http://prompt-proto-service.prompt-proto-service/next-visit
            - name: DETECTOR_CONFIG_FILE
              value: detector.yaml
            - name: KAFKA_CLUSTER
              value: 10.104.21.0:9094
            - name: CONSUMER_GROUP
              value: next-visit-fan-out-1
            - name: NEXT_VISIT_TOPIC
              value: lsst.sal.ScriptQueue.logevent_nextVisit
            - name: SASL_MECHANISM
              value: SCRAM-SHA-512
            - name: SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: kafka_pp_sasl_username
                  name: kafka-sasl-prompt-prompt-processing
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: kafka_pp_sasl_password
                  name: kafka-sasl-prompt-prompt-processing
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: http://10.106.41.77:8081
            - name: OFFSET
              value: latest
      volumes:
        - name: kafka-sasl-prompt-prompt-processing
          secret:
            secretName: kafka-sasl-prompt-prompt-processing
          